In [50]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import VotingClassifier,StackingClassifier,RandomForestClassifier
import seaborn as sns
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline

# Data Collection

In [51]:
df = pd.read_csv("train.csv")
df=df.drop(["Name","Ticket","Cabin"],axis=1)
df.head()

   PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0       3    male  22.0      1      0   7.2500        S
1            2         1       1  female  38.0      1      0  71.2833        C
2            3         1       3  female  26.0      0      0   7.9250        S
3            4         1       1  female  35.0      1      0  53.1000        S
4            5         0       3    male  35.0      0      0   8.0500        S

In [52]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age            177
SibSp            0
Parch            0
Fare             0
Embarked         2
dtype: int64

# Preprocessing

In [53]:
num_statergy = SimpleImputer(strategy="mean")
cat_statergy = SimpleImputer(strategy="most_frequent")

In [54]:
num_col = num_statergy.fit_transform(df[['Age']])
cat_col = cat_statergy.fit_transform(df[["Embarked"]])

In [55]:
df["Age"]= num_col.ravel()
df["Embarked"] = cat_col.ravel()

# Feature Engineering

In [56]:
ohe = OneHotEncoder(drop="first",sparse_output=False)
ohe_data=ohe.fit_transform(df[['Embarked']])

In [57]:
ohe_data = pd.DataFrame(ohe_data, columns=ohe.get_feature_names_out(["Embarked"]))

In [58]:
df=pd.concat([df,ohe_data],axis=1)

In [59]:
df=df.drop("Embarked",axis=1)

In [60]:
le = LabelEncoder()
le_data = le.fit_transform(df['Sex'])
df["Sex"] = le_data

# Train-Test Split

In [61]:
X = df.drop("Survived",axis=1)
y= df.Survived

In [62]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.3,random_state=42)

# Hyperparameter Tuning

In [63]:
models = {
    "LogisticRegression" : {
        "model":LogisticRegression(),
        "params":{
            "C" : [0.1,10,11,50,100],
            "max_iter":[100,1000,500]
        }
    },
    "SVC" : {
        "model": SVC(),
        "params":{
            "C" : [0.1,10,11,50,100],
            "kernel":['rbf',"linear"],
        }
    },
"KNeighborsClassifier" : {
    "model":KNeighborsClassifier(),
    "params": {
    "n_neighbors":[3,5,11,7,9]
    }
},
    "RandomForestClassifier" : {
        "model":RandomForestClassifier(),
        "params":{
             "n_estimators":[13,15,11,42],
            "criterion" : ["gini", "entropy", "log_loss"]
        
        }
    }
    
}

In [64]:
best_params = []
for model_name,md in models.items():
    GScv = GridSearchCV(md["model"],md["params"])
    pipe = Pipeline([("scale",StandardScaler()),("GScv",GScv)])
    pipe.fit(X_train,y_train)
    best_params.append({
        "model":model_name,
        "score":pipe.named_steps["GScv"].best_score_,
        "params": pipe.named_steps["GScv"].best_params_,
    })

best_params = pd.DataFrame(best_params)    
best_params

                    model     score                                     params
0      LogisticRegression  0.802542                {'C': 0.1, 'max_iter': 100}
1                     SVC  0.794568                 {'C': 10, 'kernel': 'rbf'}
2    KNeighborsClassifier  0.812181                         {'n_neighbors': 7}
3  RandomForestClassifier  0.813819  {'criterion': 'gini', 'n_estimators': 42}

## Model Training

# 1) LogisticRegression

In [65]:
log_reg = LogisticRegression(C= 0.1, max_iter= 100)
pipe = Pipeline([("scale",StandardScaler()),("log_reg",log_reg)])
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
accuracy_score(y_test,y_pred)

0.8059701492537313

# 2) SVC

In [66]:
svc = SVC(C=50)
pipe = Pipeline([("scale",StandardScaler()),("svc",svc)])
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
accuracy_score(y_test,y_pred)

0.7910447761194029

# 3) knn

In [67]:
knn = KNeighborsClassifier(n_neighbors= 7)
pipe = Pipeline([("scale",StandardScaler()),("knn",knn)])
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
accuracy_score(y_test,y_pred)

0.8134328358208955

# 4) RandomForestClassifier

In [68]:
rfc = RandomForestClassifier(criterion= 'entropy', n_estimators= 11)
pipe = Pipeline([("scale",StandardScaler()),("rfc",rfc)])
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
accuracy_score(y_test,y_pred)

0.8134328358208955

# 5) VotingClassifier

In [69]:
vc = VotingClassifier([("lr",log_reg),("svc",svc),("knn",knn)])
pipe = Pipeline([("scale",StandardScaler()),("vc",vc)])
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)
accuracy_score(y_test,y_pred)

0.8097014925373134

# 6) StackingClassifier

In [70]:
st = StackingClassifier([("lr",log_reg),("svc",svc),("kn",kn)],final_estimator=LogisticRegression())
pipe = Pipeline([("scale",StandardScaler()),("vc",st)])
pipe.fit(X_train,y_train)
y_pred=pipe.predict(X_test)
accuracy_score(y_test,y_pred)

0.8059701492537313